Update package.json
sqlite 5.1.4 update Dec 2022, broke the wac. -> fixed to 5.1.2
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found